project:
  build:
    timestamp: 0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: task-tool-demo

task-tool:
  #版本号
  version: 1
  #单位ms
  run-time-base: 10
  #安全key
  security-key: tasktooltest
  taskToolCentral:
    open: true
#    apiUrl: https://task-tool-demo.opendfl.org.cn
    apiUrl: http://localhost:8080
    authKey: tasktooltest
    taskLocal:
      type: test
      code: test
      ip: localhost
      port: 8080
  #统计时间类型
  counterTimeTypes:
    - code: MI
      name: 'Minute'
      time-seconds: 60
      date-format: ddHHmm
      hisCount: 5
    - code: H
      name: 'Hour'
      time-seconds: 3600
      hisCount: 5
    - code: D
      name: 'Day'
      time-seconds: 86400
      hisCount: 5
    - code: T
      name: 'Total'
      time-seconds: -1

logging:
  level:
    root: INFO
    cn:
      org:
        opendfl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

