spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

task-tool:
  #版本号
  version: 1
  #单位ms
  run-time-base: 10
  #安全key
  security-key: tasktooltest
  #统计时间类型
  counterTimeTypes:
    - code: M
      time-seconds: 60
      name: 'Minute'
    - code: H
      time-seconds: 3600
      name: 'Hour'
    - code: D
      time-seconds: 86400
      name: 'Day'
    - code: T
      time-seconds: -1
      name: 'Total'

logging:
  level:
    root: INFO
    org:
      ccs:
        opendfl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

